In [1]:
import numpy as np
import pandas as pd
import ast

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
credits.head(1)

movie_id   title                                               cast  \
0     19995  Avatar  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   
2                                   Spectre          6.3       4466   206647   
3                     The Dark Knight Rises          7.6       9106    49026   
4                               John Carter          6.1       2124    49529   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [7]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action','Adventure','Fantasy','SciFi']

In [14]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        return L

In [15]:
movies['genres'] = movies['genres'].apply(convert)

In [16]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                               cast  \
0   [culture clash]  [{"cast_id": 242, "character": "Jake Sully", "...   
1           [ocean]  [{"cast_id": 4, "character": "Captain Jack Spa...   
2             [spy]  [{"cast_id": 1, "character": "James Bond", "cr...   
3       [dc comics]  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [based on novel]  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [19]:
import ast

def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L


In [20]:
movies['cast'] = movies['cast'].apply(convert3)

In [21]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [22]:
import ast

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L


In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [25]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [28]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])


In [29]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

         keywords                                           cast  \
0  [cultureclash]  [SamWorthington, ZoeSaldana, SigourneyWeaver]   
1         [ocean]     [JohnnyDepp, OrlandoBloom, KeiraKnightley]   
2           [spy]      [DanielCraig, ChristophWaltz, LéaSeydoux]   
3      [dccomics]      [ChristianBale, MichaelCaine, GaryOldman]   
4  [basedonnovel]    [TaylorKitsch, LynnCollins, SamanthaMorton]   

                 crew  
0      [JamesCameron]  
1     [GoreVerbinski]  
2         [SamMendes]  
3  [ChristopherNolan]  
4     [AndrewStanton]

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

         keywords                                           cast  \
0  [cultureclash]  [SamWorthington, ZoeSaldana, SigourneyWeaver]   
1         [ocean]     [JohnnyDepp, OrlandoBloom, KeiraKnightley]   
2           [spy]      [DanielCraig, ChristophWaltz, LéaSeydoux]   
3      [dccomics]      [ChristianBale, MichaelCaine, GaryOldman]   
4  [basedonnovel]    [TaylorKitsch, LynnCollins, SamanthaMorton]   

                 crew                                               tags  
0      [JamesCameron]  [In, the, 22nd, century,, a, paraplegic, Marin...  
1     [GoreVerbinski]  [Captain, Barbossa,, long, believed, to, be, d...  
2         [SamMendes]  [A, cryptic, message, from, Bond’s, past, send...  
3  [ChristopherNolan]  [Following, the, death, of, District, Attorney...  
4     [AndrewStanton]  [John, Carter, is, a, war-weary,, former, mili...

In [32]:
new_df = movies[['movie_id','title','tags']]

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/var/folders/y0/ns6w9p9s3xsgtd351773x_gw0000gn/T/ipykernel_98133/3089450492.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))


In [34]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [35]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/var/folders/y0/ns6w9p9s3xsgtd351773x_gw0000gn/T/ipykernel_98133/3214958533.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())


In [37]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

In [38]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action cultureclash samworthington zoesaldana sigourneyweaver jamescameron'

In [39]:
new_df['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure ocean johnnydepp orlandobloom keiraknightley goreverbinski'

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [41]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [43]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [44]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
import nltk

In [47]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [48]:
def stem(text):
    list=[]
    for i in text.split():
        list.append(ps.stem(i))
        return " ".join(list)

In [49]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action cultureclash samworthington zoesaldana sigourneyweaver jamescameron')

'in'

In [50]:
new_df['tags'] = new_df['tags'].apply(stem)

/var/folders/y0/ns6w9p9s3xsgtd351773x_gw0000gn/T/ipykernel_98133/3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [51]:
new_df

movie_id                                     title      tags
0        19995                                    Avatar        in
1          285  Pirates of the Caribbean: At World's End   captain
2       206647                                   Spectre         a
3        49026                     The Dark Knight Rises    follow
4        49529                               John Carter      john
...        ...                                       ...       ...
4804      9367                               El Mariachi        el
4805     72766                                 Newlyweds         a
4806    231617                 Signed, Sealed, Delivered  "signed,
4807    126186                          Shanghai Calling      when
4808     25975                         My Date with Drew      ever

[4806 rows x 3 columns]

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.04902903, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.03874921, 0.        ,
        0.        ],
       [0.04902903, 0.        , 1.        , ..., 0.03224129, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03874921, 0.03224129, ..., 1.        , 0.05405405,
        0.055577  ],
       [0.        , 0.        , 0.        , ..., 0.05405405, 1.        ,
        0.055577  ],
       [0.        , 0.        , 0.        , ..., 0.055577  , 0.055577  ,
        1.        ]])

In [54]:
cosine_similarity(vectors).shape

(4806, 4806)

In [55]:
similarity = cosine_similarity(vectors)

In [56]:
similarity

array([[1.        , 0.        , 0.04902903, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.03874921, 0.        ,
        0.        ],
       [0.04902903, 0.        , 1.        , ..., 0.03224129, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03874921, 0.03224129, ..., 1.        , 0.05405405,
        0.055577  ],
       [0.        , 0.        , 0.        , ..., 0.05405405, 1.        ,
        0.055577  ],
       [0.        , 0.        , 0.        , ..., 0.055577  , 0.055577  ,
        1.        ]])

In [57]:
similarity[0]

array([1.        , 0.        , 0.04902903, ..., 0.        , 0.        ,
       0.        ])

In [58]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.03874921, 0.        ,
       0.        ])

In [59]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(3606, 0.2525907427704613),
 (4405, 0.25),
 (529, 0.19062321291575585),
 (311, 0.17407765595569785),
 (151, 0.16666666666666666)]

In [60]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
         print(new_df.iloc[i[0]].title)

In [61]:
recommend('Batman Begins')

The Dark Knight Rises
Raising Helen
The Dark Knight
Batman Forever
Synecdoche, New York


In [62]:
new_df.iloc[3606].title

'Apollo 18'

In [63]:
import pickle

In [64]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [65]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [66]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [67]:
pickle.dump(similarity,open('similarity.pkl','wb'))